world: GameWorld
data-location: data/<worldname>
game:
  init-size: 4001
  final-size: 101
  episode-length: 20
  mins-to-shrink: 120
  team-mode: false
  respect-teams: true
  uhc-mode: true
  spread-distance: 150
db:
  host: localhost
  port: 3306
  database: OverwatchLeague
  username: Krusher99
  password: password_is_not_a_good_password