world: GameWorld
event-name: Event Name
# Where to store game data
data-location: data/<worldname>
game-start-tips: false
tips: false
allow-command-blocks: false

# The plugin will also consider players in the game world's Nether and End by looking at suffixes if this is true. This is best explained by an example.
# EXAMPLE:
# Game World: world001
# Plugin will also include players in world001_nether and world001_the_end
extended-world-detection: true

### Game Options ###
game:
  init-size: 4001
  final-size: 101
  episode-length: 20
  mins-to-shrink: 120
  team-mode: false
  respect-teams: true
  uhc-mode: true
  spread-distance: 150

# Optional Database Information
db:
  host: localhost
  port: 3306
  database: OverwatchLeague
  username: Krusher99
  password: password_is_not_a_good_password