name: UHC_Automation
version: 1.2.5
author: CactusPuppy
description: Automates the handling of UHC events
main: usa.cactuspuppy.uhc_automation.Main

commands:
  uhcprep:
    description: Performs the setup to create a lobby.
    aliases: [prep, uhcp]
  uhcstart:
    description: Starts the UHC. No big surprises.
    aliases: [start, uhcs]
    usage: /<command> [secs to start]
    permission: uhca.admin
  uhcoptions:
    description: Edits options regarding the game. See wiki for more details.
    aliases: [options, uhco]
    usage: /<command> <option> [value]
    permission: uhca.admin
  uhcreset:
    description: Stops the game and resets everything.
    aliases: [reset, uhcr, uhcstop]
    usage: /<command>
    permission: uhca.admin
  uhcsetworld:
    description: Sets the world the executor is in to be where the UHC is occurring
    aliases: [setworld, uhcworld]
    usage: /<command>
    permission: uhca.admin
  uhcstatus:
    description: Dumps game status to log files
    aliases: [status]
    usage: /<command>
    permission: uhca.admin
  uhctime:
    description: Tells user the time elapsed in the UHC
    usage: /<command>
  uhcunreg:
    description: Unregsiters a player from the database. Player cannot be registered again unless /uhcreg is used.
    aliases: [unreg, unregsiter, uhcunregister]
    usage: /<command> [player]
    permission: uhca.admin
  uhcreg:
    description: Registers an online player in the database
    aliases: [reg, register, uhcregister]
    usage: /<command> [player]
    permission: uhca.admin