name: UHC_Automation
version: 1.6
author: CactusPuppy
description: Automates the handling of UHC events
main: usa.cactuspuppy.uhc_automation.Main
api-version: 1.13

commands:
  uhcprep:
    description: Performs the setup to create a lobby.
    aliases: [prep, uhcp]
  uhcstart:
    description: Starts the UHC. No big surprises.
    aliases: [start, uhcs]
    usage: /<command> [secs to start]
    permission: uhca.admin
  uhcoptions:
    description: Edits options regarding the game. See wiki for more details.
    aliases: [options, uhco]
    usage: /<command> <option> <value>
    permission: uhca.admin
  uhcreset:
    description: Stops the game and resets everything.
    aliases: [reset, uhcr, uhcstop]
    usage: /<command>
    permission: uhca.admin
  uhcsetworld:
    description: Sets the world the executor is in to be where the UHC is occurring
    aliases: [setworld, uhcworld]
    usage: /<command>
    permission: uhca.admin
  uhcstatus:
    description: Tells user the game status
    aliases: [status]
    usage: /<command>
    permission: uhca.admin
  uhcinfo:
    description: Tells user information about the game
    usage: /<command> ["toggle"/"chat"/"scoreboard"]
  uhcunreg:
    description: Unregsiters a player from the database. Player cannot be registered again unless /uhcreg is used.
    aliases: [unreg, unregsiter, uhcunregister]
    usage: /<command> <player>
    permission: uhca.admin
  uhcreg:
    description: Registers an online player in the database
    aliases: [reg, register, uhcregister]
    usage: /<command> <player>
    permission: uhca.admin
  uhcrules:
    description: Tells the rules to the player
    aliases: [rules]
    usage: /<command>
  uhchelp:
    description: Links to the GitHub wiki
    usage: /<command>