name: UHC_Automation
version: 1.7
author: CactusPuppy
description: Automates the handling of UHC-style events
main: usa.cactuspuppy.uhc_automation.Main
api-version: 1.13

commands:
  uhc:
    description: Access UHC_Automation's functionality.
    usage: /<command> <subcommand> [args]