name: UHC_Automation
version: 0.2
author: CactusPuppy
description: Automates the handling of UHC events
main: usa.cactuspuppy.uhc_automation.Main

commands:
  uhcprep:
    description: Performs the setup to create a lobby.
    aliases: [prep, uhcp]
  uhcstart:
    description: Starts the UHC. No big surprises.
    aliases: [start, uhcs]
    usage: /<command> [secs to start]
    permission: uhca.admin
  uhcoptions:
    description: Edits options regarding the game. See wiki for more details.
    aliases: [options, uhco]
    usage: /<command> <option> [value]
    permission: uhca.admin
  uhcreset:
    description: Stops the game and resets everything.
    aliases: [reset, uhcr, uhcstop]
    usage: /<command>
    permission: uhca.admin
  uhcsetworld:
    description: Sets the world the executor is in to be where the UHC is occurring
    aliases: [setworld, uhcworld]
    usage: /<command>
    permission: uhca.admin
  uhcstatus:
    description: Dumps game status to log files
    aliases: [status]
    usage: /<command>
    permission: uhca.admin