name: UHC_Automation
version: 0.1
author: CactusPuppy
description: Automates the handling of UHC commands
main: usa.cactuspuppy.uhc_automation.Main

commands:
  uhcstart:
    description: Starts the UHC. No big surprises.
    aliases: [start, uhcs]
    usage: /<command> [secs to start]
    permission: uhca.admin
  uhcoptions:
    description: Edits options regarding the game. See wiki for more details.
    aliases: [options, uhco]
    usage: /<command> <option> [value]
    permission: uhca.admin
  uhcreset:
    description: Stops the game and resets everything.
    aliases: [reset, uhcr, uhcstop]
    usage: /<command>