name: UHC_Automation
version: 2.0
author: CactusPuppy
description: Automates the handling of UHC-style events
main: usa.cactuspuppy.uhc_automation.Main
api-version: 1.13

commands:
  uhc:
    description: Access UHC_Automation's functionality.
    usage: /<command> <subcommand> [args]
permissions:
  uhc.admin:
    default: op
    description: Allows holder to start, stop, and modify the UHC