name: UHC Automation
version: 0.1
author: puppycactus@gmail.com
main: usa.cactuspuppy.uhc_automation.Main
description: Automates the handling of UHC commands
commands:
  uhcstart:
    description: Starts the UHC. No big surprises.
    aliases: [start, uhcs]
    usage: /<command> [secs to start]
    permission: uhca.admin
  uhcoptions:
    description: Edits options regarding the game. See wiki for more details.
    aliases: [options, uhco]
    usage: /<command> <option> [value]
    permission: uhca.admin
  uhcreset:
    description: Stops the game and resets everything.
    aliases: [reset, uhcr]
    usage: /<command>